plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/sessions/epic-peaceful-knuth/mnt/Urban Wholesale/carry-to-your-door/dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]